apiVersion: v1
kind: Secret
metadata:
  name: subscriber-secret
  namespace: {{ .Release.Namespace }}
data:
  INFRA_ID: "{{ required "A valid .Values.global.infraId entry required!"  .Values.global.infraId }}"
  ACCESS_KEY: "{{ required "A valid .Values.global.accessKey entry required!" .Values.global.accessKey }}"
  CUSTOM_TLS_CERT: "{{.Values.customTlsCert}}"