apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: litmus-admin
  namespace: {{ .Release.Namespace }}
  labels:
    name: litmus-admin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: upgrade-agent-sa
  namespace: {{ .Release.Namespace }}