{{- if and (ne $.Release.Namespace $.Values.agentNamespace) $.Values.agentNamespaceCreate -}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $.Values.agentNamespace }}
  annotations:
    helm.sh/resource-policy: keep
---
{{- end }}

