{{ if  .Values.clusterScope -}} 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaos-runner
  labels:
    {{- include "ddcr-rbac.labels" . | nindent 4 }}
  {{- with .Values.clusterRoleBinding.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chaos-runner
subjects:
- kind: ServiceAccount
  name: {{ $.Values.serviceAccount.name }}
  namespace: {{- if eq $.Release.Namespace $.Values.agentNamespace }} {{ $.Release.Namespace }} {{- else }} {{ $.Values.agentNamespace }} {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaos-discovery
  labels:
    {{- include "ddcr-rbac.labels" . | nindent 4 }}
  {{- with .Values.clusterRoleBinding.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chaos-discovery
subjects:
- kind: ServiceAccount
  name: {{ $.Values.serviceAccount.name }}
  namespace: {{- if eq $.Release.Namespace  $.Values.agentNamespace }} {{ $.Release.Namespace }} {{- else }} {{ $.Values.agentNamespace }} {{- end }}
{{ end }}
---
{{ if .Values.clusterScope -}} 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaos-discovery-network-map
  labels:
    {{- include "ddcr-rbac.labels" . | nindent 4 }}
  {{- with .Values.clusterRoleBinding.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chaos-discovery-network-map
subjects:
- kind: ServiceAccount
  name:  {{ $.Values.serviceAccount.name }} 
  namespace: {{- if eq $.Release.Namespace $.Values.agentNamespace }} {{ $.Release.Namespace }} {{- else }} {{ $.Values.agentNamespace }} {{- end }}
{{ end }}
