{{- if and .Values.serviceAccount.create .Values.serviceAccount.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ddcr-rbac.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ddcr-rbac.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "ddcr-rbac.serviceAccountName" . }}
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/service-account-token
{{- end }}