{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ddcr-rbac.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ddcr-rbac.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- if .Values.serviceAccount.secret.create -}}
secrets:
  - name: {{ include "ddcr-rbac.serviceAccountName" . }}
{{- end }}
---
{{- if ne $.Release.Namespace $.Values.agentNamespace -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ddcr-rbac.serviceAccountName" . }}
  namespace: {{ $.Values.agentNamespace }}
  labels:
    {{- include "ddcr-rbac.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
{{- end }}

