tags:  
  clusterScopeMode: false
  namespaceMode: false
  crdMode: false
global:
  clusterScope:
    enabled: true
  autoUpgrade:
    enabled: true
  infraId: ""
  accessKey: ""
  workflowInstanceId: ""
  accountId: ""
  serverAddress: "https://app.harness.io/gratis/chaos/kserver/api"

subscriber:
  image:
    registry: docker.io
    repository: harness/chaos-subscriber
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.33.0"
    imagePullSecrets: []

  upgrader:
    image:
      registry: docker.io
      repository: harness/k8s-chaos-infrastructure-upgrader
      pullPolicy: Always
      # Overrides the image tag whose default is the chart appVersion.
      tag: "1.33.0"
      imagePullSecrets: []

  customTlsCert: ""
  version: 1.33.0

  skipSslVerify: "true"

  connectionType: HTTPS

  isInfraConfirmed: "false"

  isSecretEnabled: "true"

  serviceAccount: 
    name: hce

  securityContext:
    runAsUser: 2000
    runAsGroup: 2000
    allowPrivilegeEscalation: false

  resources:
    requests:
      memory: "300Mi"
      cpu: "125m"
      ephemeral-storage: "500Mi"
    limits:
      memory: "500Mi"
      cpu: "225m"
      ephemeral-storage: "1Gi"
  nodeSelector: {}
  affinity: {}
  tolerations: []

workflow-controller:
  image:
    registry: docker.io
    repository: harness/chaos-workflow-controller
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v3.4.16"
    imagePullSecrets: []

  argoExec:
    image:
      registry: docker.io
      repository: harness/chaos-argoexec
      pullPolicy: Always
      # Overrides the image tag whose default is the chart appVersion.
      tag: "v3.4.16"

  serviceAccount: 
    name: hce

  securityContext:
    runAsUser: 2000
    runAsGroup: 2000
    allowPrivilegeEscalation: false

  resources:
    requests:
      memory: "300Mi"
      cpu: "125m"
      ephemeral-storage: "500Mi"
    limits:
      memory: "500Mi"
      cpu: "225m"
      ephemeral-storage: "1Gi"
  nodeSelector: {}
  affinity: {}
  tolerations: []
chaos-operator:
  image:
    registry: docker.io
    repository: harness/chaos-operator
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.33.0"
    imagePullSecrets: []

  chaosRunner:
    image:
      registry: docker.io
      repository: harness/chaos-runner
      pullPolicy: Always
      # Overrides the image tag whose default is the chart appVersion.
      tag: "1.33.0"

  serviceAccount: 
    name: hce

  securityContext:
    runAsUser: 2000
    runAsGroup: 2000
    allowPrivilegeEscalation: false

  resources:
    requests:
      memory: "300Mi"
      cpu: "125m"
      ephemeral-storage: "500Mi"
    limits:
      memory: "500Mi"
      cpu: "225m"
      ephemeral-storage: "1Gi"
  nodeSelector: {}
  affinity: {}
  tolerations: []
chaos-exporter:
  image:
    registry: docker.io
    repository: harness/chaos-exporter
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.33.0"
    imagePullSecrets: []

  serviceAccount: 
    name: hce

  securityContext:
    runAsUser: 2000
    runAsGroup: 2000
    allowPrivilegeEscalation: false

  resources:
    requests:
      memory: "300Mi"
      cpu: "125m"
      ephemeral-storage: "500Mi"
    limits:
      memory: "500Mi"
      cpu: "225m"
      ephemeral-storage: "1Gi"
  nodeSelector: {}
  affinity: {}
  tolerations: []




