global:
  clusterScope:
    enabled: true
  autoUpgrade:
    enabled: true
  infraId: ""
  accessKey: ""
  workflowInstanceId: ""
  accountId: ""
  serverAddress: "https://app.harness.io/gratis/chaos/kserver/api"


image:
  registry: docker.io
  repository: harness/chaos-subscriber
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.32.0"
  imagePullSecrets: []

upgrader:
  image:
    registry: docker.io
    repository: harness/k8s-chaos-infrastructure-upgrader
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.32.0"
    imagePullSecrets: []


version: 1.32.0

skipSslVerify: "true"

customTlsCert: "" 

connectionType: HTTPS

isInfraConfirmed: "false"

isSecretEnabled: "true"


serviceAccount: 
  name: hce

securityContext:
  runAsUser: 2000
  runAsGroup: 2000
  allowPrivilegeEscalation: false

resources:
  requests:
    memory: "300Mi"
    cpu: "125m"
    ephemeral-storage: "500Mi"
  limits:
    memory: "500Mi"
    cpu: "225m"
    ephemeral-storage: "1Gi"

nodeSelector: {}


tolerations: []

affinity: {}


