global:
  clusterScope:
    enabled: false
  autoUpgrade:
    enabled: true
  infraId: "1234"
  accessKey: "abcd"
  workflowInstanceId: "c8a90d9f-46ee-4638-b90b-417179fe609a"
  accountId: acc
  serverAddress:  https://app.harness.io/gratis/chaos/kserver/api


image:
  registry: docker.io
  repository: chaosnative/workflow-controller
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v3.4.14"
  imagePullSecrets: []


argoExec:
  image:
    registry: docker.io
    repository: chaosnative/argoexec
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v3.4.14"

serviceAccount: 
  name: hce

securityContext:
  runAsUser: 2000
  runAsGroup: 2000
  allowPrivilegeEscalation: false

resources:
  requests:
    memory: "300Mi"
    cpu: "125m"
    ephemeral-storage: "500Mi"
  limits:
    memory: "500Mi"
    cpu: "225m"
    ephemeral-storage: "1Gi"


nodeSelector: {}


tolerations: []

affinity: {}

