global:
  clusterScope:
    enabled: true
  autoUpgrade:
    enabled: true
  infraId: ""
  accessKey: ""
  workflowInstanceId: ""
  accountId: ""
  serverAddress:  https://app.harness.io/gratis/chaos/kserver/api


image:
  registry: docker.io
  repository: chaosnative/chaos-operator
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.30.0"
  imagePullSecrets: []

chaosRunner:
  image:
    registry: docker.io
    repository: chaosnative/chaos-runner
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.30.0"

serviceAccount: 
  name: hce

securityContext:
  runAsUser: 2000
  runAsGroup: 2000
  allowPrivilegeEscalation: false

resources:
  requests:
    memory: "300Mi"
    cpu: "125m"
    ephemeral-storage: "500Mi"
  limits:
    memory: "500Mi"
    cpu: "225m"
    ephemeral-storage: "1Gi"

nodeSelector: {}


tolerations: []

affinity: {}


