apiVersion: v1
kind: Service
metadata:
  name: workflow-controller-metrics
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: metrics
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: workflow-controller