apiVersion: v1
kind: Secret
metadata:
  name: subscriber-secret
  namespace: {{ .Release.Namespace }}
data:
  ACCESS_KEY: "{{ .Values.global.accessKey }}"
  CUSTOM_TLS_CERT: "{{.Values.customTlsCert}}"
  INFRA_ID: "{{ .Values.global.infraId }}"