apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "emissary.fullname" . }}
  labels:
    {{- include "emissary.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "emissary.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "emissary.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PORTAL_URL
              value: {{ required "A valid portalURL is required!" .Values.portalURL }}
            - name: ACCOUNT_IDENTIFIER
              value: {{ required "A valid accountIdentifier is required!" .Values.accountIdentifier }}
            - name: ORGANIZATION_IDENTIFIER
              value: {{ required "A valid organizationIdentifier is required!" .Values.organizationIdentifier }}
            - name: PROJECT_IDENTIFIER
              value: {{ required "A valid projectIdentifier is required!" .Values.projectIdentifier }}
            - name: ENVIRIONMENT_IDENTIFIER
              value: {{ required "A valid environmentIdentifier is required!" .Values.environmentIdentifier }}
            - name: INFRASTRUCTURE_IDENTIFIER
              value: {{ required "A valid infrastructureIdentifier is required!" .Values.infrastructureIdentifier }}
            - name: INFRASTRUCTURE_TOKEN
              value: {{ required "A valid infrastructureToken is required!" .Values.infrastructureToken }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
